[package]
name = "git-release-name"
version = "0.1.0"
authors = ["Kevin Choubacha <chewbacha@gmail.com>"]

[dependencies]
rand = "*"
atty = "^0.2"
clap = "^2.29"
rn_dictionary = { path = "../rn-dictionary" }

[dev-dependencies]
assert_cli = "0.5"
