version: 2
jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
         keys:
           - deps-{{ checksum "Cargo.lock" }}
           - deps- # used if checksum fails
      - run:
          name: Test
          command: cargo test --all
      - save_cache:
         key: deps-{{ checksum "Cargo.lock" }}
         paths:
           - target/debug/deps

  deploy-master:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
         keys:
           - deps-{{ checksum "Cargo.lock" }}
           - deps- # used if checksum fails
      - run:
          name: Setup git user info
          command: |
            git config --global user.email "chewbacha@gmail.com"
            git config --global user.name "Kevin Choubacha"
      - run:
          name: Tag commit
          command: git tag -m "$(cargo run -p git-release-name-cli -- $(git rev-parse HEAD) -f sentence)" $(cargo run -p git-release-name-cli -- $(git rev-parse HEAD) -f kebab)
      - run:
          name: Push tag
          command: git push origin --tags
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-master:
          requires:
            - build
          filters:
            branches:
              only: master
