[package]
name = "release-name-web"
version = "0.1.0"
authors = ["Kevin Choubacha <chewbacha@gmail.com>"]

[dependencies]
rn_dictionary = { path = "../rn-dictionary" }
rocket = "0.3.6"
rocket_codegen = "0.3.6"
